version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production #Or Development
      # - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=contactSchedulerDb;Username=postgres;Password=postgres
    ports:
      - '5000:8080'
    depends_on:
      db:
        condition: service_healthy # S칩 inicia ap칩s o banco estar saud치vel
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contactSchedulerDb
    ports:
      - '5432:5432'
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres'] # Verifica se o Postgres est치 pronto
      interval: 10s # Verifica a cada 10 segundos
      timeout: 5s # Tempo limite por tentativa
      retries: 5 # Tenta 5 vezes antes de falhar

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
