version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production #Or Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=contactSchedulerDb;Username=postgres;Password=postgres
    ports:
      - '5000:80'
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contactSchedulerDb
    ports:
      - '5432:5432'
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
